import Vue from 'vue'
import Router from 'vue-router'
import PageView from '@/layouts/PageView'
import RouteView from '@/layouts/RouteView'
import GlobalLayout from '@/layouts/GlobalLayout'
// import Login from '@/pages/login/Login'